# Generated by Django 4.2.6 on 2023-10-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
